# Base image
FROM python:3.11.6-slim-bullseye
WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY server.py /app/server.py
RUN pip install --no-cache-dir --upgrade -r requirements.txt
CMD ["uvicorn", "server:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]
